name: js-sdk::publish_package

on:
  push:
    branches:
      - main

jobs:
  run-build:
    name: js-sdk::build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk-js

    steps:
      - name: js-sdk::Check out Git repository and Config User
        uses: actions/checkout@v3
      
      - run: |
            git config user.name github-actions
            git config user.email github-actions@github.com

      - name: js-sdk::Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: js-sdk::Install Node.js dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-publish:
    name: js-sdk::publish
    runs-on: ubuntu-latest
    needs: run-build
    permissions:
      contents: write
      packages: write
    defaults:
      run:
        working-directory: ./sdk-js
        
    steps:
      - name: js-sdk::Check out Git repository and Config User
        uses: actions/checkout@v3
        
      - run: |
            git config user.name github-actions
            git config user.email github-actions@github.com

      - name: js-sdk::Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: js-sdk::Publish Package
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
