name: js-sdk::checks

on:
  pull_request:
    branches:
      - dev
      - dev/*
      - main
      - main/*

jobs:
  run-build:
    name: js-sdk::build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk-js

    steps:
      - name: js-sdk::Check out Git repository
        uses: actions/checkout@v3

      - name: js-sdk::Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: js-sdk::Install Node.js dependencies
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: js-sdk::Build
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-lint:
    name: js-sdk::lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk-js

    steps:
      - name: js-sdk::Check out Git repository
        uses: actions/checkout@v3

      - name: js-sdk::Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      # ESLint and Prettier must be in `package.json`
      - name: js-sdk::Install Node.js dependencies
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: js-sdk::Run linters
        run: npm run ci:format
        
  run-test:
      name: js-sdk::test
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./sdk-js

      steps:
        - name: js-sdk::Check out Git repository
          uses: actions/checkout@v3

        - name: js-sdk::Set up Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 20

        # ESLint and Prettier must be in `package.json`
        - name: js-sdk::Install Node.js dependencies
          run: npm ci
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: js-sdk::Run tests
          run: npm run test